"""empty message

Revision ID: 546c18327d33
Revises: 
Create Date: 2023-10-16 23:06:00.068703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546c18327d33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotdeal_model',
    sa.Column('id', sa.VARCHAR(length=30), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('first_price', sa.DOUBLE(), nullable=True),
    sa.Column('last_price', sa.DOUBLE(), nullable=True),
    sa.Column('currency_type', sa.VARCHAR(length=30), nullable=True),
    sa.Column('store_link', sa.TEXT(), nullable=True),
    sa.Column('source_link', sa.TEXT(), nullable=True),
    sa.Column('scrape_at', sa.DATETIME(), nullable=True),
    sa.Column('is_done', sa.BOOLEAN(), nullable=True),
    sa.Column('is_blind', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotdeal_model')
    # ### end Alembic commands ###
